spring.application.name=api-error-lab

spring.datasource.url=jdbc:postgresql://localhost:5432/api-error-lab
spring.datasource.username=api-error-lab
spring.datasource.password=api-error-lab

ddl-auto = validate